// Buzzora legal policies — Terms & Conditions, Privacy Policy, Refund &
// Cancellation, Return, and Shipping policies, as supplied by the business.
// Content is reproduced faithfully; only obvious formatting artifacts
// (stray double punctuation, HTML entities) were cleaned up. Fields left
// blank in the source document (jurisdiction, Grievance Officer details)
// are marked TODO rather than invented — see `todo` flags below.

export const LAST_UPDATED = "24 July 2026";

export const policySections = [
  {
    id: "terms",
    nav: "Terms of Use",
    title: "Terms & Conditions",
    intro: [
      "This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signature.",
      "This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the domain name Buzzora.co.in (\"Website\"), including the related mobile site and mobile application (together, the \"Platform\").",
      {
        text: "The Platform is owned by TODO_COMPANY_NAME, with its registered office at Janglote, Jammu and Kashmir (hereinafter referred to as ‘Platform Owner’, ‘we’, ‘us’, ‘our’).",
        todo: "Business name — the source document lists this as “9186009531,” which looks like a phone number entered by mistake rather than a legal or trading name.",
      },
      "Your use of the Platform and its services and tools is governed by the following terms and conditions (“Terms of Use”), including the applicable policies incorporated herein by reference. If you transact on the Platform, you shall be subject to the policies applicable to the Platform for such transaction. By mere use of the Platform, you shall be contracting with the Platform Owner, and these Terms of Use, including the policies, constitute your binding obligations with the Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.",
      "For the purpose of these Terms of Use, wherever the context so requires, ‘you’, ‘your’ or ‘user’ shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.",
      "ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.",
    ],
    listIntro: "The use of the Platform and/or availing of our Services is subject to the following Terms of Use:",
    list: [
      "To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.",
      "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.",
      "Your use of our Services and the Platform is solely and entirely at your own risk and discretion, for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.",
      "The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents, including but not limited to the design, layout, look and graphics.",
      "You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.",
      "You agree to pay us the charges associated with availing the Services.",
      "You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or by Indian or local laws that might apply to you.",
      "You agree and acknowledge that the website and the Services may contain links to other third-party websites. On accessing these links, you will be governed by the terms of use, privacy policy and other policies of such third-party websites. These links are provided for your convenience to provide further information.",
      "You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.",
      "You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use, the Privacy Policy and other policies, or your violation of any law, rule or regulation, or the rights (including infringement of intellectual property rights) of a third party.",
      "Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.",
      "These Terms, and any dispute or claim relating to them or their enforceability, shall be governed by and construed in accordance with the laws of India.",
      {
        text: "All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in TODO_JURISDICTION.",
        todo: "Jurisdiction — left blank in the source document. Add the city/state whose courts should have exclusive jurisdiction.",
      },
      "All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.",
    ],
  },
  {
    id: "privacy",
    nav: "Privacy Policy",
    title: "Privacy Policy",
    subsections: [
      {
        heading: "Introduction",
        paragraphs: [
          {
            text: "This Privacy Policy describes how TODO_COMPANY_NAME and its affiliates (collectively “we”, “our”, “us”) collect, use, share, protect or otherwise process your information/personal data through our website Buzzora.co.in (the “Platform”). Please note that you may be able to browse certain sections of the Platform without registering with us. We do not offer any product/service under this Platform outside India, and your personal data will primarily be stored and processed in India. By visiting this Platform, providing your information, or availing any product/service offered on the Platform, you expressly agree to be bound by the terms of this Privacy Policy, the Terms of Use, and the applicable service/product terms and conditions, and agree to be governed by the laws of India, including those applicable to data protection and privacy. If you do not agree, please do not use or access our Platform.",
            todo: "Business name placeholder — same field flagged in the Terms & Conditions section above.",
          },
        ],
      },
      {
        heading: "Collection",
        paragraphs: [
          "We collect your personal data when you use our Platform, services, or otherwise interact with us during the course of our relationship, and related information provided from time to time. Some of the information we may collect includes, but is not limited to, personal data provided during sign-up or registration, such as name, date of birth, address, telephone/mobile number, email ID, and/or any information shared as proof of identity or address. Some sensitive personal data may be collected with your consent, such as your bank account, credit or debit card, or other payment instrument information, or biometric information such as facial features (in order to enable certain opted-in features on the Platform), all in accordance with applicable law. You always have the option not to provide information, by choosing not to use a particular service or feature on the Platform. We may track your behaviour, preferences and other information you choose to provide on our Platform; this information is compiled and analysed on an aggregated basis. We will also collect information related to your transactions on the Platform and with third-party business partners. Where a third-party business partner collects your personal data directly from you, you will be governed by their privacy policies; we are not responsible for their privacy practices and encourage you to read their policies before disclosing information. If you receive an email or call from anyone claiming to be from us requesting your debit/credit card PIN, net-banking or mobile-banking password, please never provide such information, and report it immediately to an appropriate law enforcement agency.",
        ],
      },
      {
        heading: "Usage",
        paragraphs: [
          "We use personal data to provide the services you request. Where we use your personal data for marketing, we will provide you the ability to opt out of such use. We use your personal data to assist sellers and business partners in handling and fulfilling orders; to enhance customer experience; to resolve disputes and troubleshoot problems; to inform you about online and offline offers, products, services and updates; to customise your experience; to detect and protect against error, fraud and other criminal activity; to enforce our Terms of Use; to conduct marketing research, analysis and surveys; and as otherwise described to you at the time your information was collected. Your access to certain products/services may be affected if the relevant permission is not provided to us.",
        ],
      },
      {
        heading: "Sharing",
        paragraphs: [
          "We may share your personal data internally within our group entities, other corporate entities, and affiliates, to provide you access to the services and products they offer; these entities may market to you as a result unless you explicitly opt out. We may disclose personal data to third parties such as sellers, business partners, and third-party service providers, including logistics partners, prepaid payment instrument issuers, and reward programs, as needed to provide our services, comply with legal obligations, enforce our user agreement, facilitate marketing activities, or prevent, detect, mitigate and investigate fraudulent or illegal activity. We may disclose personal and sensitive personal data to government agencies or other authorised law enforcement agencies where required by law, or in the good-faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders or other legal process; to enforce our Terms of Use or this Privacy Policy; to respond to claims that content violates the rights of a third party; or to protect the rights, property or personal safety of our users or the general public.",
        ],
      },
      {
        heading: "Security precautions",
        paragraphs: [
          "To protect your personal data from unauthorised access, disclosure, loss or misuse, we adopt reasonable security practices and procedures and adhere to our security guidelines, including offering the use of a secure server. However, transmission of information over the internet is not completely secure for reasons beyond our control; by using the Platform, you accept the inherent security risks of internet data transmission. You are responsible for protecting the login and password credentials for your account.",
        ],
      },
      {
        heading: "Data deletion and retention",
        paragraphs: [
          "You may delete your account via your profile and settings on the Platform, which will result in the loss of all information associated with that account. You may also write to us using the contact information below to request assistance. We may refuse or delay deletion where there is a pending grievance, claim, shipment or other service obligation. Once deleted, you will lose access to the account. We retain your personal data only for as long as required for the purpose it was collected, or as required under applicable law, except where retention is necessary to prevent fraud or future abuse, or for other legitimate purposes; we may retain anonymised data for analytical and research purposes.",
        ],
      },
      {
        heading: "Your rights",
        paragraphs: [
          "You may access, rectify and update your personal data directly through the functionality provided on the Platform.",
        ],
      },
      {
        heading: "Consent",
        paragraphs: [
          "By visiting our Platform or providing your information, you consent to the collection, use, storage, disclosure and other processing of your information in accordance with this Privacy Policy. If you disclose personal data relating to other people, you represent that you have the authority to do so. You consent to us, and our corporate entities, affiliates and partners, contacting you via SMS, instant messaging apps, call and/or email for the purposes described in this Privacy Policy. You may withdraw consent previously given by writing to the Grievance Officer below with the subject line “Withdrawal of consent for processing personal data.” We may verify such requests before acting on them. Withdrawal of consent is not retrospective and will be handled in accordance with the Terms of Use, this Privacy Policy and applicable law; we reserve the right to restrict or deny services for which such information is necessary.",
        ],
      },
      {
        heading: "Changes to this Privacy Policy",
        paragraphs: [
          "Please check this page periodically for changes. We may update this Privacy Policy to reflect changes to our information practices, and will notify you of significant changes where required under applicable law.",
        ],
      },
    ],
    grievanceOfficer: true,
  },
  {
    id: "refund-cancellation",
    nav: "Refund & Cancellation",
    title: "Refund & Cancellation Policy",
    intro: [
      "This refund and cancellation policy outlines how you can cancel or seek a refund for a product or service purchased through the Platform.",
    ],
    list: [
      "Cancellations will only be considered if the request is made within 15 days of placing the order. Cancellation requests may not be entertained if the order has already been communicated to the relevant seller/merchant and shipping has been initiated, or if the product is already out for delivery — in that case, you may choose to reject the product at the doorstep.",
      "We do not accept cancellation requests for perishable items such as food products. However, a refund or replacement can be made if you establish that the quality of the delivered product is not good.",
      "In case of receipt of damaged or defective items, please report this to our customer service team within 15 days of receipt. The request will be reviewed once the relevant seller/merchant has checked and confirmed the issue. If a product received is not as shown on the site or as expected, please notify our customer service team within 15 days of receiving the product; our team will review your complaint and take an appropriate decision.",
      "For complaints regarding products that come with a manufacturer's warranty, please refer the issue directly to the manufacturer.",
      "Approved refunds will take 15 days to be processed.",
    ],
  },
  {
    id: "returns",
    nav: "Return Policy",
    title: "Return Policy",
    intro: [
      "We offer a refund or exchange within the first 10 days from the date of purchase. If 10 days have passed since your purchase, we are unable to offer a return, exchange or refund of any kind.",
      "To be eligible for a return or exchange: (i) the purchased item must be unused and in the same condition you received it; (ii) the item must be in its original packaging; and (iii) items purchased on sale may not be eligible for return or exchange. Only items found to be defective or damaged are replaced, based on an exchange request.",
      "Certain categories of products or items may be exempt from returns or refunds; where applicable, this will be identified to you at the time of purchase. For approved exchange or return requests, once your returned item is received and inspected, we will email you to confirm receipt. If approved after our quality check, your request will be processed in accordance with our policies.",
    ],
  },
  {
    id: "shipping",
    nav: "Shipping Policy",
    title: "Shipping Policy",
    intro: [
      "Orders are shipped through registered domestic courier companies and/or speed post only. Orders are shipped within 10 days of the order and/or payment, or as per the delivery date agreed at the time of order confirmation, subject to courier company / post office norms. The Platform Owner shall not be liable for any delay in delivery by the courier company or postal authority. Delivery is made to the address provided by the buyer at the time of purchase, and delivery of our services will be confirmed to the email address provided at registration. Any shipping costs levied by the seller or the Platform Owner are non-refundable.",
    ],
  },
];
